### ISSUE TITLE
The built-in adapter for Falcon framework does not work with Python 3.11

### ISSUE THREAD

**Issue by seratch** [slackapi/bolt-python#757]
As of Nov 2022, the latest version of Falcon framework is not yet compatible with Python 3.11. When you try to run your code built with Falcon, Python 3.11 raises the following TypeError:

```
_______ ERROR collecting tests/adapter_tests_async/test_async_falcon.py ________
ImportError while importing test module '/home/runner/work/bolt-python/bolt-python/tests/adapter_tests_async/test_async_falcon.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/adapter_tests_async/test_async_falcon.py:11: in <module>
    from slack_bolt.adapter.falcon.async_resource import AsyncSlackAppResource
slack_bolt/adapter/falcon/async_resource.py:5: in <module>
    from falcon.asgi import Request, Response
/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/falcon/asgi/__init__.py:35: in <module>
    from .app import App
/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/falcon/asgi/app.py:46: in <module>
    from .response import Response
/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/falcon/asgi/response.py:17: in <module>
    from asyncio.coroutines import CoroWrapper  # type: ignore
E   ImportError: cannot import name 'CoroWrapper' from 'asyncio.coroutines' (/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/asyncio/coroutines.py)
```

There is no workaround until Falcon project releases a new version with the fix on their side.

See also:
 * https://github.com/slackapi/bolt-python/pull/751#issuecomment-1293239137
 * https://github.com/falconry/falcon/issues/2120

### Category (place an `x` in each of the `[ ]`)

* [ ] **slack_bolt.App** and/or its core components
* [ ] **slack_bolt.async_app.AsyncApp** and/or its core components
* [x] Adapters in **slack_bolt.adapter**
* [ ] Others

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by vytas7** [comment]
We'll try to cut a bugfix release (Falcon 3.1.1) ASAP (hopefully in the middle of the next week).

**Comment by seratch** [comment]
@vytas7 Thanks for sharing the update! Once the release is available, I will check if it works for us too

**Comment by vytas7** [comment]
[`3.1.1`](https://pypi.org/project/falcon/3.1.1/) is out now! Feel free to test and let us know if it works for you.

**Comment by seratch** [comment]
@vytas7 Thanks for letting us know this! I will check it out

**Comment by seratch** [comment]
It looks like that v3.1.1 works without any issues!
